---
title: "Dissertation HMM"
output: html_document
---

```{r setup, include=FALSE}
#Loaded Libraries
library(tidyverse)
library(readxl)
library(MASS)
library(moveHMM)
library(caret)
library(parallel)
```

### Load Data

The column types are set accordingly, while others are skipped.

```{r change wd}
setwd("C:/Users/mikep/OneDrive/Documents/University of Edinburgh/Dissertations/HMM Seabirds/Data")


# Read Chick rearing excel file 2011

chk11 = read_excel("Coquet_2011_chickrearing_Tern_Tracks.xlsx", sheet = 1,
                   col_types = c("date", # Date column
                                 "skip", # skip colony
                                 "text", # Species column
                                 "numeric", # Track ID
                                 "skip","skip","skip", # skip HR MIN SEC
                                 "numeric","text",     # TSECS & CONTBEH
                                 "skip","skip",  # INSTANTBEH, FORAGESUC,
                                 "skip","skip", # PREYSIZE, PREYSPECIES
                                 "skip","skip",   # PREYFATE, NOTES
                                 "numeric","numeric", # BGNX, BGNY
                                 "numeric", "numeric", # LATITUDE, LONGITUDE
                                 "numeric","numeric", #DISTKM, DIST2COL
                                 "numeric","numeric" # BRG2COL, COMPLETE
                                 )
)

# turn contbeh to factor 
chk11$CONTBEH = as.factor(chk11$CONTBEH)

# rename TRACKID to ID
chk11 = chk11 %>%
  rename(
    ID = TRACKID
  )

#chk11 = chk11[order(chk11$ID,chk11$DATE,chk11$TSECS),]
```

```{r select libraries}
# copy dataset

chk11_cl = chk11 #%>%
    #dplyr:: select(DATE,SPECIES,TRACKID,TSECS,CONTBEH,BNGX,BNGY,LATITUDE,LONGITUDE,DISTKM,DIST2COL,BRG2COL,Complete)

# Save species names
speciesnames = unique(chk11_cl$SPECIES)
```
\
We will split the initial dataframe to sub-datasets per species. A function
is defined below that serves this specific reason.\ 
```{r function get_df}
get_df = function(df, species){
  
  species = enquo(species)
  
  # Simple function to extract species 
    new_df = df %>%
            filter(SPECIES == !!species) %>%
            dplyr::select(-SPECIES)
    
    return(as.data.frame(new_df))
}
```

```{r}
# dataframe by species - 2011 chickrearing

chk11.arc = get_df(chk11_cl,speciesnames[1]) # arctic

chk11.sand = get_df(chk11_cl,speciesnames[2]) # sandwich

chk11.comm = get_df(chk11_cl, speciesnames[3]) # common

chk11.comm.arc = get_df(chk11_cl, speciesnames[4]) # unsure

chk11.rose = get_df(chk11_cl, speciesnames[5]) # roseate
```



```{r prepData}
arc11.prepdata = prepData(chk11.arc, type = "LL", coordNames = c("LONGITUDE","LATITUDE"))
```


```{r}
which(is.na(arc11.prepdata$step))
arc11.prepdata[which.max(arc11.prepdata$step),]

test =  arc11.prepdata %>% 
  filter(arc11.prepdata$CONTBEH != "END" | arc11.prepdata$CONTBEH != "End") 
```
```{r}
#experiment for starting values
hist(arc11.prepdata$step, breaks = seq(0,0.019, l = 30))

```
```{r}

hist(arc11.prepdata$angle, breaks = seq(-pi,pi,length =100))
```


BASIC 

```{r fit basic}
# 4 States for HMM
nbStates = 2

# default Initial Values for distributions
beta0 = NULL
delta0 = NULL

formula = ~1

# Distributions used
stepDist = "gamma"
angleDist = "vm"

angleMean = NULL
stationary = FALSE

# propotion of zero steps. To be used for mass at 0    
zerostepprop = length(which(arc11.prepdata == 0))/nrow(arc11.prepdata) # = 0.6139

mu0 = c(0.003,0.015)
sigma0 = c(0.005,0.005)
zeromass0 = c(zerostepprop,0.1)
stepPar0 = c(mu0, sigma0, zeromass0)

angleMean0 = c(0,0)
kappa0 = c(1,1)
anglePar0 = c(angleMean0,kappa0)

arc_basic_m = fitHMM(data = arc11.prepdata, nbStates = nbStates, stepPar0 = stepPar0, anglePar0 = anglePar0, formula = formula)
```
```{r}
#par(mfrow = c(1,2))
plot(arc_basic_m, plotCI = TRUE, plotTracks = FALSE, breaks = seq(0,0.019,l=60))
```
```{r fit test}
# NO ENDS and End
hmmtest = fitHMM(data = test, nbStates = nbStates, stepPar0 = stepPar0, anglePar0 = anglePar0, formula = formula)
```

```{r plot test}
plot(hmmtest,plotCI = T, plotTracks = FALSE, breaks = seq(0,0.019,l=60))
```

```{r confusion matrix test}
statestest = viterbi(hmmtest) %>% as.factor
recodedtest = test$CONTBEH %>%
  recode("TS" = 2, "AS" = 1, "DF" = 2) %>%
  as.factor()

conftest = confusionMatrix(statestest,recodedtest)

conftest
```

```{r confusion matrix basic}
states = viterbi(arc_basic_m) %>% as.factor()

recoded = chk11.arc$CONTBEH %>%
  recode("TS" = 2, "AS" = 1, "DF" = 2, "END" =2, "End" = 2) %>% 
  as.factor()

confusionMatrix(states, recoded)
```

```{r additional models}
disthmm = fitHMM(data = test, nbStates = nbStates, stepPar0 = stepPar0, anglePar0 = anglePar0, formula = ~ DIST2COL + BRG2COL + DISTKM + TSECS)
```

```{r AIC}
AIC(arc_basic_m, hmmtest, m1, disthmm)
```

Parallel package
```{r parallel}
set.seed(1)

n_iter = 5

ncores = detectCores() - 1
cl = makeCluster(getOption("cl.cores",ncores))

clusterExport(cl, list("arc11.prepdata","fitHMM"))

allPar0 = lapply(as.list(1:n_iter), function(x){
  
  
   stepMean0 = runif(2,
                    min = c(0.002,0.008),
                    max = c(0.005,0.015)
  )
  stepSD0 = runif(2,
                    min = c(0.001,0.001),
                    max = c(0.001,0.003)
  )
  angleMean0 = c(0,0)
  angleConc0 = runif(2,
                    min = c(0.05,1),
                    max = c(0.5,2)
  )
  
  steppar0_f = c(stepMean0, stepSD0,zeromass0)
  anglePar0_f = c(angleMean0,angleConc0)
    
  return(list(step = steppar0_f, angle = anglePar0_f))
})

model_parallel = parLapply(cl = cl, X = allPar0, fun = function(par0) {
m <- fitHMM(data = arc11.prepdata, nbStates = 2, stepPar0 = par0$step,
anglePar0 = par0$angle)

return(m)
})
```

```{r slow version}

#niter = 5
#model = list()

#for (i in 1:niter){
#  stepMean0 = runif(2,
#                    min = c(0.002,0.008),
#                    max = c(0.005,0.015)
#  )
#  stepSD0 = runif(2,
#                    min = c(0.001,0.001),
#                    max = c(0.001,0.003)
#  )
#  angleMean0 = c(0,0)
#  angleConc0 = runif(2,
#                    min = c(0.05,1),
#                    max = c(0.5,2)
#  )
#  
#  steppar0_rep = c(stepMean0, stepSD0,zeromass0)
#  anglePar0_rep = c(angleMean0,angleConc0)
#  
#  model[[i]] = fitHMM(data = arc11.prepdata, nbStates = nbStates, stepPar0 = steppar0_rep, anglePar0 = anglePar0_rep, formula = formula)
#  
#}
```


\
All values depict the same likelihood for ~1 function
```{r}
allnllk <- unlist(lapply(model_parallel, function(m) m$mod$minimum))
allnllk
```


```